[window]
dynamic_padding = true
# opacity = 0.97
# padding = { x = 0, y = 0 }

[env]
TERM = "xterm-256color"

[font]
size = 14


normal = { family = "monospace", style = "Regular" }
# normal = { family = "Iosevka Comfy Motion Fixed", style = "Medium" }
# bold = { family = "Iosevka Comfy Motion Fixed", style = "Bold" }
# italic = { family = "Iosevka Comfy Motion Fixed", style = "Medium Italic" }
# bold_italic = { family = "Iosevka Comfy Motion Fixed", style = "Bold Italic" }

[colors.primary]
background = "0x181818"
