[window]
dynamic_padding = true
# opacity = 0.97
# padding = { x = 0, y = 0 }

[env]
TERM = "xterm-256color"

[font]
size = 12

normal = { family = "Iosevka Nerd Font", style = "Medium" }
bold = { family = "Iosevka Nerd Font", style = "Bold" }
italic = { family = "Iosevka Nerd Font", style = "Medium Italic" }
bold_italic = { family = "Iosevka Nerd Font", style = "Bold Italic" }

[colors.primary]
background = "0x181818"
