[window]
dynamic_padding = true
# opacity = 0.97
# padding = { x = 0, y = 0 }

[env]
TERM = "xterm-256color"

[font]
size = 14

# normal = { family = "Hack", style = "Medium" }
# bold = { family = "Hack", style = "Bold" }
# italic = { family = "Hack", style = "Medium Italic" }
# bold_italic = { family = "Hack", style = "Bold Italic" }

normal = { family = "Berkeley Mono", style = "Regular" }
bold = { family = "Berkeley Mono", style = "Bold" }
italic = { family = "Berkeley Mono", style = "Italic" }
bold_italic = { family = "Berkeley Mono", style = "Bold Italic" }

# normal = { family = "MesloLGS Nerd Font ", style = "Regular" }
# bold = { family = "MesloLGS Nerd Font", style = "Bold" }
# italic = { family = "MesloLGS Nerd Font", style = "Italic" }
# bold_italic = { family = "MesloLGS Nerd Font", style = "Bold Italic" }

[colors.primary]
background = "0x131313"
